{
    "code": 0
    ,"msg": ""
    ,"count": 1
    ,"data": [
        {
            "id" : 7749,
            "code" : "47546be9f7f34952acf1d111a4d6f3fc",
            "vehicle_code" : "df6ddba496b444ca9061e92892ce3e76",
            "vehicle_name" : "辽MS7380",
            "name" : "左志强-预混剂",
            "type" : "",
            "length" : "1315",
            "load_weight" : "50",
            "load_volume" : "",
            "depreciation" : "",
            "vehicle_license_img" : "",
            "remaining_load_weight" : 0.00,
            "remaining_load_volume" : 0.00,
            "location_source" : 0,
            "terminal_number" : "",
            "vehicle_img" : "",
            "road_transport_certificate_number" : "",
            "vehicle_due_date" : "",
            "vehVehicleType" : "普通货车",
            "vehVehicleLength" : "",
            "vehLoadWeight" : "",
            "axisNumber" : "",
            "vehLoadVolume" : "",
            "vehicleStyleName" : "生猪运输车",
            "isIntraName" : "场内",
            "user_id" : 10298,
            "head_img" : "",
            "recommended_man" : "",
            "driver_code" : "47546be9f7f34952acf1d111a4d6f3fc",
            "driver_phone" : "13847591577",
            "identification_number" : "152326198311273614",
            "driver_name" : "左志强-预混剂",
            "fixed_phone" : "",
            "work_company" : "",
            "home_address" : "",
            "work_time" : "",
            "is_leave" : 0,
            "driver_type" : 2,
            "user_code" : "e786f5e9bb32407f9ccea04d948fc7bf",
            "is_freeze" : 0,
            "create_time" : "2019-07-22 16:07:14",
            "update_time" : "",
            "auth_status" : 3,
            "advance_fee" : 0.00,
            "auth_time" : "2019-07-22 16:09:02",
            "create_code" : "4bb92c794dc141a5b11b4a2775308ad0",
            "driver_due_date" : "",
            "link_man" : "饲料车队",
            "diffDate" : "",
            "vehicleDiffDate" : "",
            "team_name" : "王朋博",
            "team_code" : "42d0b464aafe4e249d60d48bfd71db3d",
            "plat_admin" : "plat_admin"
          }
    ]
  }